#!/usr/bin/env python3
"""Finite Python fixtures/mocks only. No compiler, generated ABI or carrier PASS."""
import copy
import importlib.util
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
from types import SimpleNamespace
from unittest import mock

sys.dont_write_bytecode = True


def load(name, filename):
    spec = importlib.util.spec_from_file_location(name, Path(__file__).with_name(filename))
    value = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(value)
    return value


collector = load('c2_pure_collector', 'apple-source-inputs.py')
builder = load('c2_pure_builder', 'ios-libbox.py')
helper = builder.source_helpers()
COUNT = 0


def check(ok, message):
    global COUNT
    if not ok:
        raise AssertionError(message)
    COUNT += 1


def rejected(action, message):
    global COUNT
    try:
        action()
    except (RuntimeError, ValueError, KeyError, OSError) as error:
        if message not in str(error):
            raise AssertionError(f'Wrong rejection: {error}; expected {message}') from error
        COUNT += 1
    else:
        raise AssertionError('Counterexample accepted: ' + message)


GO_PROTOCOLS = '''package libbox
type PlatformInterface interface {
 BindInterfaceControl(fd int32, interfaceName string) error
 LocalDNSTransport() LocalDNSTransport
 OpenTun(options TunOptions) (int32, error)
}
type CommandServerHandler interface {
 ServiceStop() error
 ServiceReload() error
}
type LocalDNSTransport interface {
 Raw() bool
 Lookup(ctx *ExchangeContext, network string, domain string) error
 Exchange(ctx *ExchangeContext, message []byte) error
}
type Func interface {
 Invoke() error
}
type InterfaceUpdateListener interface {
 UpdateDefaultInterface(name string) error
}
'''


def fixture_header():
    text = '@interface LibboxConfigValidationResult : NSObject\n'
    text += ''.join('- (NSString* _Nonnull)get' + key + ';\n' for key in collector.GETTERS) + '@end\n'
    text += 'FOUNDATION_EXPORT NSString* _Nonnull const LibboxConfigValidationContractVersion;\n'
    for key in ('NewStrictCommandServer', 'NewTransientCommandServer'):
        text += f'FOUNDATION_EXPORT LibboxCommandServer* _Nullable Libbox{key}(id<LibboxCommandServerHandler> _Nullable handler, id<LibboxPlatformInterface> _Nullable platform, NSError* _Nullable* _Nullable error);\n'
    text += 'FOUNDATION_EXPORT LibboxConfigValidationResult* _Nullable LibboxCheckConfigWithResult(NSString* _Nullable config, NSString* _Nullable request, int64_t timeout);\n'
    text += 'FOUNDATION_EXPORT NSString* _Nonnull LibboxInterfaceUpdateListenerIdentity(id<LibboxInterfaceUpdateListener> _Nullable listener);\n'
    for name, methods in {'PlatformInterface': ['bindInterfaceControl:(int32_t)fd interfaceName:(NSString* _Nullable)name error:(NSError* _Nullable*)error', 'localDNSTransport', 'openTun'],
                          'CommandServerHandler': ['serviceStop', 'serviceReload'], 'LocalDNSTransport': ['raw', 'lookup', 'exchange'],
                          'Func': ['invoke'], 'InterfaceUpdateListener': ['updateDefaultInterface']}.items():
        text += '@protocol Libbox' + name + ' <NSObject>\n' + ''.join('- (BOOL)' + method + ';\n' for method in methods) + '@end\n'
    text += '@interface LibboxExchangeContext : NSObject\n- (void)onCancel:(id<LibboxFunc> _Nullable)callback;\n@end\n'
    return text


TEMPLATES = '''var appleBindHeaderTmpl = template.Must(template.New("apple.h").Parse(`
// Objective-C API for talking to the following Go packages
//
{{range .pkgs}}//\t{{.PkgPath}}
{{end}}//
// File is generated by gomobile bind. Do not edit.
#ifndef __{{.title}}_FRAMEWORK_H__
#define __{{.title}}_FRAMEWORK_H__

{{range .bases}}#include "{{.}}.objc.h"
{{end}}
#endif
`))
var appleModuleMapTmpl = template.Must(template.New("iosmmap").Parse(`framework module "{{.Module}}" {
\theader "ref.h"
{{range .Headers}}    header "{{.}}"
{{end}}
    export *
}`))'''


def graph_fixture(root):
    shared, core, policy = builder.final_preflight()
    checkout, cache, goroot, out = [root / name for name in ('checkout', 'module-cache', 'goroot', 'ios')]
    generated = checkout / 'build/ios-arm64/Libbox'
    for path in (checkout, cache, goroot, out, generated):
        path.mkdir(parents=True, exist_ok=True)
    (checkout / 'go.mod').write_text('module github.com/sagernet/sing-box\ngo 1.25.5\n')
    (checkout / 'go.sum').write_text('mock source sums; fixture only\n')
    (generated / 'go_main.go').write_text('package main\n')
    receipt = {'mainGoModSha256': helper.file_hash(checkout / 'go.mod'), 'mainGoSumSha256': helper.file_hash(checkout / 'go.sum')}
    main_module = {'Path': 'github.com/sagernet/sing-box', 'Main': True, 'Dir': str(checkout), 'GoMod': str(checkout / 'go.mod')}
    bound = checkout / 'experimental/libbox'
    bound.mkdir(parents=True)
    (bound / 'libbox.go').write_text(GO_PROTOCOLS)
    rows = [{'ImportPath': 'github.com/sagernet/sing-box/build/ios-arm64/Libbox', 'Name': 'main', 'Dir': str(generated),
             'Module': main_module, 'GoFiles': ['go_main.go'], 'Imports': [collector.BOUND]},
            {'ImportPath': collector.BOUND, 'Name': 'libbox', 'Dir': str(bound), 'Module': main_module,
             'GoFiles': ['libbox.go'], 'Imports': []}]
    for path, version in [(d['module'], d['upstreamVersion']) for d in shared['dependencyPatches']] + list(core['sourceBuild']['transportPins'].items()):
        dependency = next((d for d in shared['dependencyPatches'] if d['module'] == path), None)
        directory = checkout / 'polaris-dependencies' / dependency['name'] if dependency else cache / path.replace('/', '_')
        directory.mkdir(parents=True)
        (directory / 'go.mod').write_text('module ' + path + '\n')
        (directory / 'p.go').write_text('package p\n')
        module = {'Path': path, 'Version': version, 'Dir': str(directory), 'GoMod': str(directory / 'go.mod')}
        if dependency:
            module['Replace'] = {'Path': './polaris-dependencies/' + dependency['name'], 'Dir': str(directory), 'GoMod': str(directory / 'go.mod')}
        rows.append({'ImportPath': path + '/fixture', 'Name': 'p', 'Dir': str(directory), 'Module': module, 'GoFiles': ['p.go']})
        rows[1]['Imports'].append(path + '/fixture')
    return SimpleNamespace(shared=shared, core=core, policy=policy, checkout=checkout, cache=cache, goroot=goroot,
                           out=out, generated=generated, receipt=receipt, rows=rows)


def inspect_fixture(fixture, rows=None):
    raw = '\n'.join(json.dumps(row) for row in (fixture.rows if rows is None else rows))
    return collector.graph(raw, fixture.checkout, fixture.generated, fixture.receipt, fixture.shared, fixture.core,
                           helper, fixture.cache, fixture.goroot, fixture.out)


def observer_mocks(root, failure=None):
    """Run the real collector orchestration with tool subprocess results mocked."""
    fixture = graph_fixture(root)
    shutil.rmtree(fixture.checkout / 'build')
    mobile, developer, support, evidence = [root / name for name in ('mobile', 'developer', 'module-cache/support', 'observations')]
    for path in (mobile, developer, support / 'cmd/gomobile', fixture.goroot):
        path.mkdir(parents=True, exist_ok=True)
    (support / 'cmd/gomobile/bind_iosapp.go').write_text(TEMPLATES)
    (support / 'bind/objc').mkdir(parents=True)
    for name in ('seq.go.support',): (support / 'bind' / name).write_text('package main\n')
    for name in ('seq_darwin.go.support', 'seq_darwin.m.support', 'ref.h', 'seq_darwin.h'):
        (support / 'bind/objc' / name).write_text('fixture source, not compiled')
    (fixture.goroot / 'version').write_text('fixture only')
    tools = {'host': {'GOPATH': str(root / 'gopath'), 'GOMODCACHE': str(fixture.cache), 'GOCACHE': str(root / 'go-cache'), 'GOROOT': str(fixture.goroot)},
             'gomobileSource': {'inventory': collector.tree_identity(support, helper)}}
    for name in ('go', 'gomobile', 'gobind', 'xcode', 'xcrun'):
        path = mobile / name;path.write_text('fixture tool, never executable')
        tools[name] = {'path': str(path), 'sha256': helper.file_hash(path)}
    tools['go']['distribution'] = collector.tree_identity(fixture.goroot, helper)
    for sdk in ('iphoneos', 'iphonesimulator'):
        path = developer / sdk;path.mkdir();(path / 'sdk.h').write_text('fixture SDK only')
        tools[sdk] = {'path': str(path), 'version': '27.1', 'buildVersion': 'fixture', 'sysroot': collector.tree_identity(path, helper)}
        for name in ('clang', 'clang++', 'swiftc'):
            path = developer / name;path.write_text('fixture compiler, never executable')
            tools[sdk][name] = {'path': str(path), 'sha256': helper.file_hash(path)}
    names, provider_checks, spawn_options, group_calls = [], [], [], []
    active_group = {}
    original_copytree = shutil.copytree
    interrupted_copy = fixture.checkout / 'build/ios-arm64/Libbox'
    copy_error = 'fixture copy interrupted after creating owned destination'

    def copied_tree(source, destination, *args, **kwargs):
        if failure == 'copy' and Path(destination) == interrupted_copy:
            interrupted_copy.mkdir(exist_ok=True)
            (interrupted_copy / 'partial.go').write_text('partial copy; never compiled')
            raise OSError(copy_error)
        return original_copytree(source, destination, *args, **kwargs)

    def verified_checkout(*_args):
        provider_checks.append(not (fixture.checkout / 'build').exists()
                               and not list(evidence.glob('polaris-c2-owned-*')))

    def observed_tools(commands, *_args):
        if failure == 'prebirth':raise RuntimeError('fixture before any source tool')
        commands.env.update({key: tools['host'][key] for key in ('GOPATH', 'GOMODCACHE', 'GOCACHE')})
        commands.executables[tools['iphoneos']['swiftc']['path']] = 'swiftc'
        return tools, support

    def fake_process(argv, cwd, env, stdout, stderr, **kwargs):
        names.append(argv)
        spawn_options.append(kwargs)
        output, error_output, code = '', '', 0
        if '-lang=go,objc' in argv:
            out = Path(next(arg.removeprefix('-outdir=') for arg in argv if arg.startswith('-outdir='))) / 'src/gobind'
            out.mkdir(parents=True)
            for name in ('go_main.go', 'go_libboxmain.go'):(out / name).write_text('package main\n')
            (out / 'Libbox.objc.h').write_text(fixture_header())
            for name in ('Universe.objc.h', 'ref.h', 'Libbox_darwin.m', 'seq_darwin.go', 'seq_darwin.m', 'seq_darwin.h'):(out / name).write_text('fixture source, not compiled')
            (out / 'seq.go').write_text('package main\n')
        elif argv[1:3] == ['env', '-json']:
            actual = dict(env, GOENV='')
            if failure == 'environment':actual['CGO_CFLAGS'] = 'wrong simulator/device input'
            output = json.dumps(actual)
        elif argv[1:4] == ['list', '-deps', '-json']:
            rows = copy.deepcopy(fixture.rows)
            rows[0]['Dir'] = str(cwd)
            rows[0]['ImportPath'] = 'github.com/sagernet/sing-box/' + Path(cwd).relative_to(fixture.checkout).as_posix()
            if failure == 'graph':rows.pop()
            output = '\n'.join(json.dumps(row) for row in rows)
        elif argv[1] == '-typecheck':
            if failure == 'swift':code, error_output = 1, 'fixture real-consumer conformance failure'
            if failure == 'tool-drift':Path(tools['go']['path']).write_text('changed fixture tool')
            if failure == 'sdk-drift':(Path(tools['iphoneos']['path']) / 'sdk.h').write_text('changed fixture SDK')
        else:raise AssertionError('unexpected mock operation: ' + repr(argv))
        stdout.write(output.encode());stderr.write(error_output.encode())
        pid = 4500 + len(names)
        wait = mock.Mock(return_value=code)
        if argv[1:4] == ['list', '-deps', '-json'] and failure in ('descendants', 'group-unknown', 'group-live', 'timeout', 'timeout-group-unknown'):
            active_group.update({'pgid': pid, 'live': True, 'unknown': failure.endswith('unknown')})
            if failure.startswith('timeout'):
                wait.side_effect = [subprocess.TimeoutExpired(argv, 1), -9]
        return SimpleNamespace(pid=pid, wait=wait)

    def fake_killpg(pgid, sig):
        group_calls.append((pgid, sig))
        if pgid == active_group.get('pgid'):
            if active_group['unknown']:raise PermissionError('fixture process group state unknown')
            if sig == collector.signal.SIGKILL:
                if failure != 'group-live':active_group['live'] = False
                return
            if active_group['live']:return
        raise ProcessLookupError('fixture process group absent')

    with mock.patch.object(collector.platform, 'system', return_value='Darwin'), \
            mock.patch.object(collector, 'observe_tools', side_effect=observed_tools), \
            mock.patch.object(collector.subprocess, 'Popen', side_effect=fake_process), \
            mock.patch.object(collector.os, 'killpg', side_effect=fake_killpg), \
            mock.patch.object(collector.time, 'monotonic', side_effect=iter(range(10000))), \
            mock.patch.object(collector.time, 'sleep'), \
            mock.patch.object(collector.shutil, 'copytree', side_effect=copied_tree), \
            mock.patch.object(helper, 'validate_source_receipt'), mock.patch.object(helper, 'provider', return_value=object()), \
            mock.patch.object(helper, 'verify_checkout', side_effect=verified_checkout) as verify:
        action = lambda: collector.collect(builder.final_preflight, lambda: helper, fixture.checkout, fixture.receipt,
                                           Path(tools['go']['path']), mobile, developer, evidence)
        if failure == 'copy':
            caught = None
            try:
                action()
            except Exception as error:
                caught = str(error)
            report = json.loads((evidence / 'source-observations.json').read_bytes())
            cleanup = report['cleanup']
            audit = {'caught': caught, 'originalError': report.get('error'), 'cleanupError': report.get('cleanupError'),
                     'partialCopyGone': not interrupted_copy.exists(), 'scratchGone': cleanup.get('scratchRemoved') is True,
                     'providerVerifiedAfterRemoval': cleanup.get('providerCheckoutVerifiedAfterRemoval') is True,
                     'providerChecksAfterRemoval': provider_checks, 'removedTargetCopies': cleanup['removedTargetCopies']}
            check(caught == copy_error and report['status'] == 'failed' and report.get('error') == copy_error
                  and 'cleanupError' not in report and not interrupted_copy.exists()
                  and not (fixture.checkout / 'build').exists() and not list(evidence.glob('polaris-c2-owned-*'))
                  and cleanup.get('scratchRemoved') is True and cleanup.get('providerCheckoutVerifiedAfterRemoval') is True
                  and cleanup['removedTargetCopies'] == [str(interrupted_copy)]
                  and verify.call_count == 2 and provider_checks == [True, True],
                  'partial-copy failure removes owned copy/scratch and retains original error: ' + json.dumps(audit, sort_keys=True))
            return
        if failure == 'prebirth':
            rejected(action, 'fixture before any source tool')
            report = json.loads((evidence / 'source-observations.json').read_bytes())
            cleanup = report['cleanup']
            check(report['commands'] == [] and report['commandsLogSha256'] is None
                  and cleanup['registeredProcessGroups'] == [] and cleanup['pendingProcessGroups'] == []
                  and cleanup['pendingCleanup'] is False and cleanup['processGroupsDrained'] is True
                  and cleanup['scratchRemoved'] is True and cleanup['providerCheckoutVerifiedAfterRemoval'] is True
                  and verify.call_count == 2 and provider_checks == [True, True], 'zero tool births have empty group custody and ordinary owned cleanup')
            return
        if failure in ('descendants', 'group-unknown', 'group-live', 'timeout', 'timeout-group-unknown'):
            rejected(action, 'tool failed' if failure.startswith('timeout') else 'descendants remain')
            report = json.loads((evidence / 'source-observations.json').read_bytes())
            row, cleanup = report['commands'][-1], report['cleanup']
            unknown = failure.endswith('unknown') or failure == 'group-live'
            check(row['registeredProcessGroup'] == active_group['pgid'] and row['groupDrained'] is not unknown
                  and row.get('timeout', False) == failure.startswith('timeout')
                  and (row.get('groupPresentAfterParentExit') is True if not failure.startswith('timeout') else True)
                  and all(options == {'close_fds': True, 'start_new_session': True} for options in spawn_options)
                  and all(pgid in {4500 + index for index in range(1, len(names) + 1)} for pgid, _sig in group_calls)
                  and (active_group['pgid'], collector.signal.SIGKILL) in group_calls,
                  'registered group is drained or explicitly unknown even after parent exit/timeout')
            check(report['status'] == 'failed' and (evidence / row['stdout']).read_text().startswith('{')
                  and (evidence / row['stderr']).read_bytes() == b'' and row['env']['GOENV'] == 'off',
                  'group failure preserves raw tool output, argv/environment and failed status')
            if unknown:
                check(cleanup['pendingCleanup'] is True and cleanup['processGroupsDrained'] is False
                      and cleanup['pendingProcessGroups'] == [active_group['pgid']]
                      and cleanup['scratchRemoved'] is False and Path(cleanup['scratch']).is_dir()
                      and (interrupted_copy / 'go_main.go').is_file() and (fixture.checkout / 'build').is_dir()
                      and cleanup['retainedTargetCopies'] == [{'path': str(interrupted_copy), 'inode': interrupted_copy.stat().st_ino}]
                      and len(cleanup['retainedParents']) == 2 and cleanup['removedTargetCopies'] == []
                      and cleanup['removedParents'] == [] and cleanup['sharedCachesRemoved'] is False
                      and 'providerCheckoutVerifiedAfterRemoval' not in cleanup and verify.call_count == 1
                      and provider_checks == [True], 'unknown group retains exact owned target/parents/scratch and pending cleanup')
                return
            check(cleanup['processGroupsDrained'] is True and cleanup['providerCheckoutVerifiedAfterRemoval'] is True,
                  'known group drain permits cleanup after a failed tool observation')
        elif failure:
            rejected(action, {'graph': 'truncated dependency', 'swift': 'tool failed', 'environment': 'environment differs',
                              'tool-drift': 'input hash drift', 'sdk-drift': 'sysroot hash drift'}[failure])
            report = json.loads((evidence / 'source-observations.json').read_bytes())
            check(report['status'] == 'failed' and report['cleanup']['providerCheckoutVerifiedAfterRemoval'], 'mock failure closes observer scope and verifies provider after cleanup')
        else:
            report = action()
            check(len(report['targets']) == 3 and len([argv for argv in names if '-lang=go,objc' in argv]) == 2
                  and len([argv for argv in names if '-typecheck' in argv]) == 3, '2 generation/3 graph/full-consumer Swift orchestration')
            check(all(len([arg for arg in argv if arg.endswith('.swift')]) == 5 for argv in names if '-typecheck' in argv), 'every Swift command keeps 4 consumers + witness')
            check(report['carrierAdmission'] is False and len(report['C3Required']) == 4
                  and all('carrierCount' not in target and 'buildInfo' not in target
                          and target['effectiveEnvironment']['GOENV'] == 'off' and target['actualGoEnvironment']['GOENV'] == ''
                          for target in report['targets'].values())
                  and all(row['env']['GOENV'] == 'off' and json.loads((evidence / row['stdout']).read_bytes())['GOENV'] == ''
                          for row in report['commands'] if row['name'].endswith('-effective-go-env')),
                  'C3 carrier/whole implementation never synthesized; input off/effective empty stay raw')
        check(verify.call_count == 2 and not (fixture.checkout / 'build').exists()
              and not list(evidence.glob('polaris-c2-owned-*')), 'created copies/parents/scratch removed; two provider checks')
        check((evidence / 'generated-ios/src/gobind/Libbox_darwin.m').is_file(), 'implementation source retained for C3')


def tool_observer_tests(root):
    shared, _, policy = builder.final_preflight()
    go, mobile, developer, goroot, cache = [root / name for name in ('go', 'mobile', 'developer', 'goroot', 'module-cache')]
    go.write_text('fixture tool only')
    for path in (mobile, developer / 'usr/bin', goroot, cache / 'gomobile', developer / 'iphoneos', developer / 'iphonesimulator'):
        path.mkdir(parents=True, exist_ok=True)
        (path / 'fixture').write_text('fixture bytes')
    for name in ('gomobile', 'gobind'):(mobile / name).write_text('fixture tool only')
    for name in ('clang', 'clang++', 'swiftc'):(developer / name).write_text('fixture compiler only')
    (developer / 'usr/bin/xcodebuild').write_text('fixture info tool only')
    (cache / 'gomobile/go.mod').write_text('module github.com/sagernet/gomobile\n')
    host = {'GOROOT': str(goroot), 'GOMODCACHE': str(cache), 'GOPATH': str(root / 'gopath'), 'GOCACHE': str(root / 'go-cache'),
            'GOHOSTOS': 'darwin', 'GOHOSTARCH': 'arm64', 'GOOS': 'darwin', 'GOARCH': 'arm64'}
    module = {'Path': 'github.com/sagernet/gomobile', 'Version': 'v0.1.12', 'Dir': str(cache / 'gomobile'),
              'GoMod': str(cache / 'gomobile/go.mod'), 'Sum': 'h1:fixture-only'}
    original_hash = helper.file_hash

    class FakeInfoCommands:
        def __init__(self, failure):
            self.failure, self.env, self.executables = failure, {}, {}

        def run(self, name, _args, _cwd):
            if name == 'go-version':return 'go version go1.25.' + ('4' if self.failure == 'go' else '5') + ' darwin/arm64\n'
            if name == 'go-host':return json.dumps(dict(host, GOHOSTARCH='amd64') if self.failure == 'host' else host)
            if name in ('gomobile-buildinfo', 'gobind-buildinfo'):
                tool = name.removesuffix('-buildinfo')
                version = 'v0.1.13' if self.failure == 'mobile' else 'v0.1.12'
                path = 'github.com/sagernet/gomobile/cmd/' + ('wrong' if self.failure == 'path' else tool)
                raw = f'{mobile / tool}: go1.25.5\n\tpath\t{path}\n\tmod\tgithub.com/sagernet/gomobile\t{version}\th1:fixture-only\n'
                return raw + ('\t=>\t./replacement\n' if self.failure == 'replacement' else '')
            if name == 'gomobile-source':
                row = dict(module)
                if self.failure == 'support-version':row['Version'] = 'v0.1.13'
                if self.failure == 'support-sum':row['Sum'] = 'h1:other-fixture'
                if self.failure == 'support-dir':row['Dir'] = str(root)
                return json.dumps(row)
            if name == 'actual-support-package-dirs':
                return '\n'.join(json.dumps({'ImportPath': 'github.com/sagernet/gomobile/' + package,
                                  'Dir': str(cache / 'gomobile' / package), 'Module': module}) for package in ('bind', 'bind/objc'))
            if name == 'xcode-version':return 'Xcode fixture version\n'
            if name.endswith('-path'):return str(root if self.failure == 'sdk-path' else developer / name.removesuffix('-path'))
            if name.endswith('-version') and ('clang' not in name and 'swift' not in name):return 'wrong' if self.failure == 'sdk-version' else '27.1'
            if name.endswith('-build'):return 'fixture-sdk-build'
            if name.endswith('-clang'):return str(developer / 'clang')
            if name.endswith('-swiftc'):return str(developer / 'swiftc')
            if name.endswith('-clang-version') or name.endswith('-swift-version'):return 'fixture compiler version'
            raise AssertionError('unexpected information query: ' + name)

    with mock.patch.object(helper, 'file_hash', side_effect=lambda p: '0' * 64 if str(p) == '/usr/bin/xcrun' else original_hash(p)):
        tools, support = collector.observe_tools(FakeInfoCommands(None), go, mobile, developer, shared, policy, helper, root)
        check(tools['iphoneos']['sysroot']['files'] and tools['gobind']['buildInfo']['modules']['github.com/sagernet/gomobile']['version'] == 'v0.1.12'
              and support == cache / 'gomobile', 'tool/SDK information parser uses actual fixture filesystem inventories')
        for failure, message in [('go', 'pinned host Go'), ('host', 'host/ambient'), ('mobile', 'mobile tool'), ('path', 'mobile tool'),
                                 ('replacement', 'mobile tool'), ('support-version', 'support module'), ('support-sum', 'checksum differs'),
                                 ('support-dir', 'source escapes'), ('sdk-path', 'SDK escapes'), ('sdk-version', 'SDK identity')]:
            rejected(lambda failure=failure: collector.observe_tools(FakeInfoCommands(failure), go, mobile, developer, shared, policy, helper, root), message)


def pure_tests():
    check(collector.json_stream(' {"n":1}\n{"n":2} ') == [{'n': 1}, {'n': 2}], 'multi-record stream')
    for raw, message in [('', 'empty'), ('  ', 'empty'), ('{', 'truncated'), ('{}x', 'truncated'), ('[]', 'non-object'), ('{"n":1,"n":2}', 'duplicate')]:
        rejected(lambda raw=raw: collector.json_stream(raw), message)
    for value, expected in [('15.0', 0x000f0000), ('27.1', 0x001b0100), ('17.0.1', 0x00110001)]:
        check(collector.packed_version(value) == expected, 'packed SDK version')
    for value in ('', '27', '-1.0', '27.1.0.0', 27):
        rejected(lambda value=value: collector.packed_version(value), 'invalid')
    for value in ('65536.0', '27.256', '27.1.256'):
        rejected(lambda value=value: collector.packed_version(value), 'overflow')
    shared, core, policy = builder.final_preflight()
    base = {'GOPATH': '/shared', 'GOWORK': 'off', 'GOTOOLCHAIN': 'local', 'GOENV': 'off'}
    for target in policy['targets'].values():
        env = collector.target_env(base, target, '/SDK/' + target['sdk'], '/clang', '15.0', '/output')
        actual = dict(env, GOENV='')
        collector.validate_target_env(actual, env)
        check(env['GOOS'] == 'ios' and ('simulator' in env['CGO_CFLAGS']) == bool(target['variant']), 'target platform environment')
        for key in ('GOARCH', 'DARWIN_SDK', 'CGO_CFLAGS', 'CGO_LDFLAGS', 'CC', 'CGO_ENABLED'):
            bad = dict(actual, **{key: 'wrong'})
            rejected(lambda bad=bad: collector.validate_target_env(bad, env), key)
    for value in (None, '/Users/fixture/Library/Application Support/go/env', 'off', ' '):
        rejected(lambda value=value: collector.validate_target_env(dict(actual, GOENV=value), env), 'GOENV')
    missing = dict(actual);missing.pop('GOENV')
    rejected(lambda: collector.validate_target_env(missing, env), 'GOENV')
    rejected(lambda: collector.validate_target_env(actual, dict(env, GOENV='')), 'GOENV')
    bad_target = dict(policy['targets']['ios-arm64'], sdk='iphonesimulator')
    rejected(lambda: collector.target_env(base, bad_target, '/SDK', '/clang', '15.0', '/out'), 'SDK/variant')
    rejected(lambda: collector.target_env(base, policy['targets']['ios-arm64'], '/SDK with space', '/clang', '15.0', '/out'), 'quoting')
    header = fixture_header()
    check(collector.check_headers(header, [GO_PROTOCOLS])['fullProtocolsCheckedFromSelectedSource'], 'full protocol/header fixture')
    for getter in collector.GETTERS:
        rejected(lambda getter=getter: collector.check_headers(header.replace('get' + getter + ';', 'missing' + getter + ';'), [GO_PROTOCOLS]), 'getter')
        rejected(lambda getter=getter: collector.check_headers(header.replace('@interface LibboxConfigValidationResult : NSObject\n', '@interface LibboxConfigValidationResult : NSObject\n- (void)set' + getter + ':(NSString*)value;\n'), [GO_PROTOCOLS]), 'setter')
    for old, new, message in [('NSString* _Nonnull)getRequestID', 'NSString* _Nullable)getRequestID', 'getter'),
                              ('LibboxNewStrictCommandServer(', 'UntrustedFactory(', 'factory'),
                              ('LibboxNewTransientCommandServer(', 'UntrustedFactory(', 'factory'),
                              ('NSError* _Nullable* _Nullable', 'NSError* _Nonnull* _Nonnull', 'factory'),
                              ('LibboxCheckConfigWithResult(', 'UntrustedValidation(', 'validation factory'),
                              ('int64_t timeout', 'int32_t timeout', 'validation factory'),
                              ('LibboxConfigValidationContractVersion;', 'MissingVersion;', 'constant'),
                              ('LibboxInterfaceUpdateListenerIdentity(', 'FakeIdentity(', 'listener identity'),
                              ('onCancel:', 'missingCancel:', 'OnCancel'), ('(BOOL)serviceReload;', '(BOOL)missingReload;', 'protocol method')]:
        rejected(lambda old=old,new=new: collector.check_headers(header.replace(old, new), [GO_PROTOCOLS]), message)
    rejected(lambda: collector.check_headers('/*' + header + '*/', [GO_PROTOCOLS]), 'getter')
    rejected(lambda: collector.check_headers(header, [GO_PROTOCOLS.replace('type Func interface', 'type Missing interface')]), 'protocol')
    rejected(lambda: collector.check_headers(header + '@protocol LibboxFunc <NSObject>\n- (BOOL)invoke;\n@end\n', [GO_PROTOCOLS]), 'duplicate')
    umbrella, modulemap = collector.render_headers(TEMPLATES)
    check('#include "Libbox.objc.h"' in umbrella and 'header "Universe.objc.h"' in modulemap and '{{' not in umbrella + modulemap, 'real-shape header templates')
    rejected(lambda: collector.render_headers(TEMPLATES.replace('appleModuleMapTmpl', 'missingMap')), 'template missing')
    rejected(lambda: collector.render_headers(TEMPLATES.replace('export *', '{{unknown}}')), 'unsupported')
    check(all('result.get' + getter + '()' in collector.witness() for getter in collector.GETTERS), 'finite Swift witness getters')
    with tempfile.TemporaryDirectory(prefix='polaris-c2-pure-') as temp:
        root = Path(temp)
        fixture = graph_fixture(root)
        observation = inspect_fixture(fixture)
        check(len(observation['patchedModules']['requiredLinked']) == 2 and len(observation['transportModules']['requiredLinked']) == 6, 'full2+6 graph fixture')
        absent = copy.deepcopy(fixture.rows)
        removed = absent.pop(2)['ImportPath']
        absent[1]['Imports'].remove(removed)
        result = inspect_fixture(fixture, absent)
        check(len(result['patchedModules']['allowedAbsent']) == 1 and result['absenceEvidence'][removed.rsplit('/', 1)[0]]['graphFingerprint'] == result['graphFingerprint'], 'absence binds complete target graph/source selection')
        mutations = []
        for field in ('Error', 'DepsErrors', 'Incomplete'):
            bad = copy.deepcopy(fixture.rows);bad[1][field] = {'Err': 'mock compile/load error'};mutations.append((bad, 'graph has errors'))
        bad = copy.deepcopy(fixture.rows);bad.append(copy.deepcopy(bad[-1]));mutations.append((bad, 'duplicate/missing'))
        mutations.append((copy.deepcopy(fixture.rows[:-1]), 'truncated dependency'))
        bad = copy.deepcopy(fixture.rows);bad[0]['Name'] = 'not_main';mutations.append((bad, 'generated main'))
        bad = copy.deepcopy(fixture.rows);bad[0]['Module']['GoMod'] = str(root / 'other.mod');mutations.append((bad, 'main module'))
        bad = copy.deepcopy(fixture.rows);bad[2]['Module']['Replace']['Dir'] = str(root);mutations.append((bad, 'replacement'))
        bad = copy.deepcopy(fixture.rows);bad[2]['Module']['Replace']['Path'] = '/absolute/replacement';mutations.append((bad, 'replacement'))
        bad = copy.deepcopy(fixture.rows);bad[2]['Module'].pop('Replace');mutations.append((bad, 'replacement'))
        bad = copy.deepcopy(fixture.rows);bad[4]['Module']['Version'] = 'v0.0.0';mutations.append((bad, 'transport version'))
        bad = copy.deepcopy(fixture.rows);bad[4]['Module']['Replace'] = {'Path': 'fake'};mutations.append((bad, 'unexpected module'))
        bad = copy.deepcopy(fixture.rows);bad[4].pop('Module');mutations.append((bad, 'module identity missing'))
        bad = copy.deepcopy(fixture.rows);bad[1]['GoFiles'] = ['../go.mod'];mutations.append((bad, 'source file path'))
        bad = copy.deepcopy(fixture.rows);bad[1]['GoFiles'] = ['missing.go'];mutations.append((bad, 'source file missing'))
        bad = copy.deepcopy(fixture.rows);bad[1]['Imports'] = ['missing/module'];mutations.append((bad, 'truncated dependency'))
        bad = copy.deepcopy(fixture.rows);bad[1]['Imports'].pop();mutations.append((bad, 'unreachable'))
        bad = copy.deepcopy(fixture.rows);bad[1]['CgoLDFLAGS'] = ['missing.a'];mutations.append((bad, 'static library missing'))
        for rows, message in mutations:
            rejected(lambda rows=rows: inspect_fixture(fixture, rows), message)
        saved = (fixture.checkout / 'go.mod').read_text();(fixture.checkout / 'go.mod').write_text(saved + '// drift\n')
        rejected(lambda: inspect_fixture(fixture), 'GoMod/GoSum hash')
        (fixture.checkout / 'go.mod').write_text(saved)
        old = dict(observation['sourceHashes'])
        file = fixture.checkout / 'experimental/libbox/libbox.go';file.write_text(GO_PROTOCOLS + '// drift\n')
        rejected(lambda: collector.verify_hashes(old, helper), 'hash drift')
        inventory = root / 'inventory';inventory.mkdir();(inventory / 'one').write_text('one');(inventory / 'outside').symlink_to(root / 'external-nonexistent')
        identity = collector.tree_identity(inventory, helper)
        check(identity['entries'] == 2 and next(v for v in identity['files'] if v['path'] == 'outside')['symlink'], 'no external symlink traversal')
        (inventory / 'one').write_text('two')
        check(identity['inventorySha256'] != collector.tree_identity(inventory, helper)['inventorySha256'], 'actual directory bytes influence identity')
        evidence = root / 'evidence';evidence.mkdir()
        commands = collector.Commands(evidence, {}, {'/go': 'go', '/swift': 'swiftc', '/gobind': 'gobind', '/clang': 'clang', '/usr/bin/xcrun': 'xcrun'})
        for argv in (['/go', 'run', 'main.go'], ['/go', 'test', './...'], ['/go', 'build', '-buildmode=c-archive'],
                     ['/go', 'env', '-w', 'GOPROXY=remote'], ['/go', 'list', '-e', '-json', '.'],
                     ['/swift', '-emit-executable', 'Main.swift'], ['/swift', '-typecheck', 'shim.swift'],
                     ['/gobind', 'bind', '-o', 'Libbox.xcframework'], ['/clang', '-fsyntax-only', 'fake.m'],
                     ['/usr/bin/xcrun', 'simctl', 'boot', 'device'], ['/core', 'run'], ['/go']):
            rejected(lambda argv=argv: commands.run('forbidden', argv, root), 'forbidden tool')
        fake = SimpleNamespace(returncode=1, stdout='original partial output', stderr='original failure')

        def fake_failure(_args, stdout, stderr, **_kwargs):
            stdout.write(fake.stdout.encode());stderr.write(fake.stderr.encode())
            return SimpleNamespace(pid=4701, wait=mock.Mock(return_value=fake.returncode))

        with mock.patch.object(collector.subprocess, 'Popen', side_effect=fake_failure), \
                mock.patch.object(collector.os, 'killpg', side_effect=ProcessLookupError):
            rejected(lambda: commands.run('failure', ['/go', 'version'], root), 'tool failed')
        check((evidence / '001.stdout').read_text() == fake.stdout and (evidence / '001.stderr').read_text() == fake.stderr
              and json.loads((evidence / 'commands.json').read_bytes())[0]['exit'] == 1, 'raw nonzero logs retained')
        timeout_child = SimpleNamespace(pid=4702, wait=mock.Mock(side_effect=[subprocess.TimeoutExpired(['/go'], 1), -9]))
        with mock.patch.object(collector.subprocess, 'Popen', return_value=timeout_child), \
                mock.patch.object(collector.os, 'killpg', side_effect=ProcessLookupError):
            rejected(lambda: commands.run('timeout', ['/go', 'version'], root), 'tool failed')
        check('error' in json.loads((evidence / 'commands.json').read_bytes())[-1], 'timeout is non-PASS')
        with mock.patch.object(collector.shutil, 'disk_usage', return_value=SimpleNamespace(free=1)):
            rejected(lambda: commands.run('disk-low', ['/go', 'version'], root), 'less than 5 GiB')
    with mock.patch.object(collector.platform, 'system', return_value='Linux'), mock.patch.object(collector.subprocess, 'run', side_effect=AssertionError('compiler reached')):
        rejected(lambda: collector.collect(builder.final_preflight, builder.source_helpers, Path('/missing'), {}, Path('/go'), Path('/mobile'), Path('/developer'), Path('/evidence')), 'Mac source compiler window')
    check(builder.final_preflight()[2]['evidenceScope'] == 'source-inputs-only', 'default policy unchanged')
    rejected(builder.artifact_preflight, 'artifact evidence not implemented')
    for failure in (None, 'graph', 'swift', 'environment', 'tool-drift', 'sdk-drift', 'copy',
                    'prebirth', 'descendants', 'group-unknown', 'group-live', 'timeout', 'timeout-group-unknown'):
        with tempfile.TemporaryDirectory(prefix='polaris-c2-mock-window-') as temp:
            observer_mocks(Path(temp), failure)
    with tempfile.TemporaryDirectory(prefix='polaris-c2-mock-tools-') as temp:
        tool_observer_tests(Path(temp))


if __name__ == '__main__':
    # Tool subprocesses are forbidden throughout every fixture/mutation case.
    with mock.patch.object(collector.subprocess, 'run', side_effect=AssertionError('unexpected tool invocation')), \
            mock.patch.object(collector.subprocess, 'Popen', side_effect=AssertionError('unexpected tool spawn')), \
            mock.patch.object(collector.os, 'killpg', side_effect=AssertionError('unexpected process group signal')), \
            mock.patch.object(collector.shutil, 'disk_usage', return_value=SimpleNamespace(free=10 * 1024**3)):
        pure_tests()
    print(f'{COUNT} Apple source input unit cases passed; no compiler, Framework or App built.')
