import { emit } from '@tauri-apps/api/event';
import runtimeCoexFixture from './src/contracts/coex-runtime.rust.fixture.json';
/**
 * 保真验证 harness（仅本机验证用，不进产物）：mockIPC 喂 demo 数据 → 渲染真实 <App>。
 * headless Blink 下 nav 可点、下拉/弹窗可开，用于逐屏对拍原型 + 验证修复。
 * 命令字符串取自 domain/ipc-channels.ts。
 *
 * demo 数据本体在 `./harness-fixture`——拆出去的理由（以及它为什么必须带类型标注）见那个文件的头注：
 * 数据留在本文件里 = 任何自动化都碰不到它（本文件 import 即执行 createRoot），契约漂移只能等真机白屏。
 */
import React from 'react';
import ReactDOM from 'react-dom/client';
import { mockIPC } from '@tauri-apps/api/mocks';
import { i18nReady, syncLanguageChoice } from './src/i18n';
import './src/styles/index.css';
import App from './src/App';
import { DEMO_CONFIG, DEMO_SERVERS } from './harness-fixture';
import type { CoexSnapshot } from './src/contracts/coex-snapshot';
import rustCoexFixture from './src/contracts/coex-snapshot.rust.fixture.json';
import rustWindowsFixture from './src/contracts/coex-windows.rust.fixture.json';
import { TOPOLOGY_OTHERS_KEY, type ConnectionsAggregate } from './src/contracts/types';

// 交互验证不能把配置夹具当只读快照：DNS 资源的增删改都经 config_save 整份回写，
// 随后的 config_get 必须读到新值，否则受控表单会被旧夹具立即覆盖。
// Opt-in COEX browser fixture only. The mounted App still uses the real API wrapper,
// ipc-client envelope decoder and card. This never exercises native Rust collection.
const coexFixtureEnabled = new URLSearchParams(window.location.search).has('coex-snapshot-fixture');
const known = <T,>(value: T): { status: 'known'; value: T } => ({ status: 'known', value });
const unknown = (reason: string): { status: 'unknown'; reason: string } => ({ status: 'unknown', reason });
function coexFixture(): CoexSnapshot {
  return {
    schemaVersion: 1, platform: 'linux', observation: known({ elapsedMillis: 17, atomic: false }),
    commandCleanup: known('noRetainedSnapshotCommand'),
    context: { observationPhase: unknown('fixture phase unavailable'), ownInterfaces: unknown('fixture attribution unavailable'),
      criteria: unknown('fixture criteria unavailable'), repairHistory: unknown('fixture history unavailable') },
    classification: unknown('fixture classification not performed'),
    objects: known([{
      interface: 'fixture-tun0', tunnel: known(true), virtualization: unknown('fixture link kind unavailable'),
      stableIdentity: known(null), addresses: known([{ address: '10.77.2.9', prefixLen: 24 }]),
      routes: known([{ prefix: '0.0.0.0/1', table: known(100), scope: known('global'), role: unknown('fixture role unverified') }]),
      policyRules: known([{ priority: 120, lookupTable: known(100), addressFamily: known('ipv4'),
        selectorScope: known({ kind: 'limited', selector: 'from 10.77.2.0/24' }), appliesToObject: unknown('fixture association unverified') }]),
    }]),
  };
}
const coexPending: Array<{ resolve: (value: unknown) => void; reject: (reason: Error) => void }> = [];
const coexControl = {
  calls: [] as Array<{ command: string; payload: unknown }>,
  holdRegistration: false,
  rejectRegistration: false,
  registrationReleases: [] as Array<() => void>,
  unregisterCount: 0,
  releaseRegistration: () => { coexControl.holdRegistration = false; for (const release of coexControl.registrationReleases.splice(0)) release(); },
  fixture: coexFixture,
  runtimeState: (name: keyof typeof runtimeCoexFixture.states) => structuredClone(runtimeCoexFixture.states[name]),
  emitRuntimeState: (value: unknown) => emit('event:coexRuntimeState', value),
  // Generated by the actual Rust collector + unchanged wire functions; mock transport only.
  serializedFixture: (name: keyof typeof rustCoexFixture.snapshots) => structuredClone(rustCoexFixture.snapshots[name]),
  serializedWindowsFixture: (name: keyof typeof rustWindowsFixture.snapshots) => structuredClone(rustWindowsFixture.snapshots[name]),
  setLanguage: (language: string) => syncLanguageChoice(language),
  reply: (value: unknown) => {
    const pending = coexPending.shift();
    if (!pending) throw new Error('No pending fixture request');
    pending.resolve(value);
  },
  reject: (message: string) => {
    const pending = coexPending.shift();
    if (!pending) throw new Error('No pending fixture request');
    pending.reject(new Error(message));
  },
};
declare global { interface Window { __coexHarness?: typeof coexControl } }
if (coexFixtureEnabled) window.__coexHarness = coexControl;

let demoConfig = structuredClone(DEMO_CONFIG);
const meshIngressFixture = new URLSearchParams(window.location.search).has('mesh-inbound-fixture');
const meshIngressStorageKey = 'polaris-harness-mesh-inbound';
if (meshIngressFixture) {
  const stored = window.sessionStorage.getItem(meshIngressStorageKey);
  if (stored) demoConfig = JSON.parse(stored) as typeof DEMO_CONFIG;
  else demoConfig.servers.push({
    id: 'mesh-ingress-ts', name: 'Mesh ingress test', protocol: 'tailscale',
    address: '', port: 0, tailscaleSettings: {},
  });
}

/**
 * 首页连接流向的保真数据源：64 个目标足以覆盖默认 16 槽与最大化运行态 40 槽。
 * 先在完整集合过滤、再按调用方 slots 投影；harness 也不能把绘制预算误装成检索真值。
 */
const DEMO_TOPOLOGY_TARGETS = Array.from({ length: 64 }, (_, index) => ({
  name: `target-${String(index + 1).padStart(2, '0')}.example`,
  count: 64 - index,
}));

function demoTopology(payload: unknown): ConnectionsAggregate {
  const args = payload as { query?: string; slots?: number } | null;
  const query = args?.query?.trim().toLowerCase() ?? '';
  const slots = Math.max(4, Math.min(128, Math.floor(args?.slots ?? 16)));
  const matching = DEMO_TOPOLOGY_TARGETS.filter((target) => target.name.toLowerCase().includes(query));
  const total = matching.reduce((sum, target) => sum + target.count, 0);
  const overflow = matching.length > slots;
  const visibleCount = overflow ? slots - 1 : matching.length;
  const recentCount = overflow ? Math.ceil(visibleCount / 3) : 0;
  const mainCount = visibleCount - recentCount;
  const main = matching.slice(0, mainCount);
  const recent = matching.slice(mainCount, visibleCount);
  const hidden = matching.slice(visibleCount);
  const hosts: ConnectionsAggregate['hosts'] = [
    ...main.map((target) => ({
      ...target,
      flows: [{ outbound: 'HK', count: target.count }],
      recent: false,
    })),
    ...recent.map((target) => ({
      ...target,
      flows: [{ outbound: 'HK', count: target.count }],
      recent: true,
    })),
  ];
  if (hidden.length > 0) {
    const hiddenCount = hidden.reduce((sum, target) => sum + target.count, 0);
    hosts.push({
      name: TOPOLOGY_OTHERS_KEY,
      count: hiddenCount,
      flows: [{ outbound: 'HK', count: hiddenCount }],
      recent: false,
    });
  }
  return {
    total,
    hosts,
    outbounds: total > 0 ? [{ name: 'HK', count: total }] : [],
    at: Date.now(),
  };
}

mockIPC((cmd, payload) => {
  if (coexFixtureEnabled) {
    coexControl.calls.push({ command: cmd, payload });
    if (cmd === 'coex_readonly_snapshot' || cmd === 'coex_runtime_get_state' || cmd === 'coex_runtime_refresh') {
      return new Promise<unknown>((resolve, reject) => coexPending.push({ resolve, reject }));
    }
  }
  switch (cmd) {
    case 'config_get': return Promise.resolve(demoConfig);
    case 'config_save': {
      const next = (payload as { config?: typeof DEMO_CONFIG } | null)?.config;
      if (next) demoConfig = structuredClone(next);
      return Promise.resolve({ status: 'saved', version: 'harness' });
    }
    case 'config_get_privacy_mode': return Promise.resolve(false);
    case 'config_get_value': return Promise.resolve((demoConfig as unknown as Record<string, unknown>)[(payload as { key: string })?.key] ?? null);
    case 'config_set_value': {
      const args = payload as { key?: string; value?: unknown } | null;
      if (args?.key) {
        demoConfig = { ...demoConfig, [args.key]: args.value };
      }
      return Promise.resolve(null);
    }
    case 'server_get_all': return Promise.resolve(demoConfig.servers);
    case 'system_list_network_interfaces': return Promise.resolve([]);
    case 'server_update': {
      const server = (payload as { server?: typeof DEMO_SERVERS[number] } | null)?.server;
      if (!server) return Promise.reject(new Error('missing server'));
      demoConfig.servers = demoConfig.servers.map((existing) => existing.id === server.id ? structuredClone(server) : existing);
      if (meshIngressFixture) window.sessionStorage.setItem(meshIngressStorageKey, JSON.stringify(demoConfig));
      return Promise.resolve(null);
    }
    case 'app_presets_list': return Promise.resolve([]);
    case 'rule_resources_list': return Promise.resolve([]);
    // 契约是 RuleResourceCatalogResult（{items, fetchedAt, source}），不是裸数组——回 [] 会让
    // 资源库/添加应用两个弹窗读 `catalog.items.filter` 时炸在 undefined 上。
    case 'rule_resources_get_catalog': return Promise.resolve({ items: [], fetchedAt: null, source: 'builtin' });
    case 'proxy_get_status': return Promise.resolve(
      meshIngressFixture || coexFixtureEnabled ? { running: false } : { running: true, startTime: Date.now() - 300_000 },
    );
    case 'stats_subscribe': return Promise.resolve(null);
    case 'stats_unsubscribe': return Promise.resolve(null);
    case 'stats_project_topology': return Promise.resolve(demoTopology(payload));
    case 'renderer_log': return Promise.resolve(null);
    case 'plugin:os|platform': return Promise.resolve(coexFixtureEnabled ? 'linux' : 'macos');
    default: return Promise.resolve(null);
  }
}, { shouldMockEvents: true }); // 开事件模拟：verify 脚本用 emit() 喂 EVENT_CONNECTIONS_AGGREGATE 等推送事件

// Explicit browser-fixture only: delay acknowledgement after the actual event mock registers.
// This exercises listenReady's late-registration cleanup through the actual card effect.
if (coexFixtureEnabled) {
  const internals = (window as unknown as { __TAURI_INTERNALS__: { invoke: (cmd: string, args?: Record<string, unknown>) => Promise<unknown> } }).__TAURI_INTERNALS__;
  const original = internals.invoke;
  internals.invoke = async (cmd, args) => {
    if (cmd === 'plugin:event|listen' && args?.event === 'event:coexRuntimeState' && coexControl.rejectRegistration) throw new Error('fixture COEX listener registration rejected');
    const value = await original(cmd, args);
    if (args?.event === 'event:coexRuntimeState') {
      if (cmd === 'plugin:event|listen' && coexControl.holdRegistration) await new Promise<void>(resolve => coexControl.registrationReleases.push(resolve));
      if (cmd === 'plugin:event|unlisten') coexControl.unregisterCount++;
    }
    return value;
  };
}

void i18nReady.then(async () => {
  if (meshIngressFixture) {
    const [{ useAppStore }, { default: TsSettingsDialog }] = await Promise.all([
      import('./src/store/app-store'), import('./src/components/dialogs/TsSettingsDialog'),
    ]);
    await useAppStore.getState().loadConfig(true);
    ReactDOM.createRoot(document.getElementById('root')!).render(
      <TsSettingsDialog serverId="mesh-ingress-ts" />,
    );
  } else {
    ReactDOM.createRoot(document.getElementById('root')!).render(
      <React.StrictMode>
        <App />
      </React.StrictMode>,
    );
  }
});
